[toolchain]
channel = "1.76"                     # Avoid specifying a patch version here
components = ["rustfmt", "clippy"]
targets = ["wasm32-unknown-unknown"]
profile = "default"                  # optional: default, minimal, or complete
